openapi: 3.0.0
info:
  title: IOS-XE switches connector
  description: Connector API to Cisco IOS-XE switches
  contact:
    email: daniele.rossi@vem.com
  version: 1.0.0
servers:
- url: /
paths:
  /vlan:
    get:
      summary: get vlans
      description: |
        Get all vlans on a switch.
      operationId: get_vlan
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: ios_xe_switch_connector.controllers.default_controller
  /interface/vlan:
    post:
      summary: create vlan
      description: |
        Create a vlan for a device interface
      operationId: create_vlan
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VlanInfo'
        required: true
      responses:
        "201":
          description: ok
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: ios_xe_switch_connector.controllers.default_controller
components:
  schemas:
    VlanInfo:
      required:
      - interface_name
      - vlan_number
      type: object
      properties:
        vlan_number:
          type: integer
        interface_name:
          type: string

